version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tripmakin-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tripmakin
      SPRING_DATASOURCE_USERNAME: tripmakin
      SPRING_DATASOURCE_PASSWORD: tripmakin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:latest
    container_name: tripmakin-db
    restart: always
    environment:
      POSTGRES_DB: tripmakin
      POSTGRES_USER: tripmakin
      POSTGRES_PASSWORD: tripmakin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tripmakin-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
